USE [master]
GO

/****** Object:  Database [dannie]    Script Date: 15.04.2025 22:00:11 ******/
CREATE DATABASE [dannie]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'dannie', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\dannie.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'dannie_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\dannie_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [dannie].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [dannie] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [dannie] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [dannie] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [dannie] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [dannie] SET ARITHABORT OFF 
GO

ALTER DATABASE [dannie] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [dannie] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [dannie] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [dannie] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [dannie] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [dannie] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [dannie] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [dannie] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [dannie] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [dannie] SET  DISABLE_BROKER 
GO

ALTER DATABASE [dannie] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [dannie] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [dannie] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [dannie] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [dannie] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [dannie] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [dannie] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [dannie] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [dannie] SET  MULTI_USER 
GO

ALTER DATABASE [dannie] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [dannie] SET DB_CHAINING OFF 
GO

ALTER DATABASE [dannie] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [dannie] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [dannie] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [dannie] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [dannie] SET QUERY_STORE = OFF
GO

ALTER DATABASE [dannie] SET  READ_WRITE 
GO

